AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an S3 bucket in eu-north-1 and ap-northeast-1 in a remote account
Parameters:
  ResRoleArn:
    Type: String
    Description: The IAM role name for the role that is trusted by the destination role.
  DevRoleArn: 
    Type: String
    Description: The IAM role to be assumed and used to create a CloudFormation stack containing an S3 bucket.
Resources:
 ECSService:
  Type: AWS::ECS::Service
  Properties: 
   CapacityProviderStrategy:
     - CapacityProvider: FARGATE
   Cluster: ept2-backend-integ-test
   DesiredCount: 2
   HealthCheckGracePeriodSeconds: 0
   LaunchType: FARGATE
   LoadBalancers: 
     - ContainerName: ept2-backend-integ-test
       ContainerPort: 8080
       LoadBalancerName: ept2-integ-test-alb
       TargetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:607911488832:targetgroup/ept2-backend-integ-test/a09b3e24d12ba381
   NetworkConfiguration: 
     AwsvpcConfiguration: 
      AssignPublicIp: ENABLED
      SecurityGroups: 
       - sg-01d053a5d35d6c5a0
      Subnets: 
       - subnet-00e7c7672cda7417b
   PropagateTags: SERVICE
   SchedulingStrategy: REPLICA
   ServiceArn: arn:aws:ecs:eu-west-1:607911488832:service/ept2-backend-integ-test
   ServiceName: ept2-backend-integ-test
   ServiceRegistries: 
     - ContainerName: ept2-backend-integ-test
       ContainerPort: 4200
   TaskDefinition: ept2-backend-integ-test:10
Outputs:
  DestinationAccountId:
    Value: !GetAtt ECSService.AccountId
